version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout:
          path: plugins/fse-studio
      - run:
          name: Linting PHP
          working_directory: plugins/fse-studio
          command: |
            npm run installation
            npm run lint:php
      - run:
          name: Linting JS and CSS
          working_directory: plugins/fse-studio
          command: |
            npm run lint:js
            npm run lint:css
  phpunit:
    machine:
      image: ubuntu-2004:202111-02

    steps:
      - checkout:
          path: plugins/fse-studio
      - run:
          name: Install PHP
          working_directory: plugins/fse-studio
          command: |
            sudo apt -y install php7.4
      - run:
          name: Install Composer
          working_directory: plugins/fse-studio
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            EXPECTED_SIGNATURE=$(curl -s https://composer.github.io/installer.sig)
            ACTUAL_SIGNATURE=$(php -r "echo hash_file('sha384', 'composer-setup.php');")
            [[ "$EXPECTED_SIGNATURE" == "$ACTUAL_SIGNATURE" ]] && sudo php composer-setup.php --install-dir=/bin --filename=composer || exit 1
      - run:
          name: PHPUnit Integration Tests
          working_directory: plugins/fse-studio
          command: |
            npm run installation
            npm run test:phpunit || true

workflows:
  build:
    jobs:
      - lint
      - phpunit
