version: 2.1

orbs:
  php: circleci/php@1.1.0

jobs:
  lint:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout:
          path: plugins/fse-studio
      - run:
          name: Linting PHP
          working_directory: plugins/fse-studio
          command: |
            npm run installation
            npm run lint:php
      - run:
          name: Linting JS and CSS
          working_directory: plugins/fse-studio
          command: |
            npm run lint:js
            npm run lint:css
  phpunit:
    machine:
      image: ubuntu-2004:202111-02

    steps:
      - checkout:
          path: plugins/fse-studio
      - php/install-php
      - php/install-composer
      - run:
          name: PHPUnit Integration Tests
          working_directory: plugins/fse-studio
          command: |
            npm run installation
            npm run test:phpunit || true

workflows:
  build:
    jobs:
      - lint
