version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout:
          path: plugins/fse-studio
      - run:
          name: Linting PHP
          command: |
            npm run installation
            npm run lint:php
      - run:
          name: Linting JS and CSS
          working_directory: plugins/fse-studio
          command: |
            npm run lint:js
            npm run lint:css

workflows:
  build:
    jobs:
      - lint
