version: 2.1

orbs:
  node: circleci/node@5.0
  php: circleci/php@1.1
  wp-svn: studiopress/wp-svn@0.2

references:
  PLUGIN_PATH: &PLUGIN_PATH
    plugins/pattern-manager

jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: *PLUGIN_PATH
      - run:
          name: Installing Pluginade
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh install
      - setup_remote_docker
      - run:
          name: Linting PHP
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh lint:php
      - run:
          name: Linting JS and CSS
          working_directory: *PLUGIN_PATH
          command: |
            sh pluginade.sh lint:js
            sh pluginade.sh lint:css
  test-js:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: *PLUGIN_PATH
      - run:
          name: Installing Pluginade
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh install
      - setup_remote_docker
      - run:
          name: Testing JS
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh test:js
  phpunit:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: *PLUGIN_PATH
      - run:
          name: Installing Pluginade
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh install
      - setup_remote_docker
      - run:
          name: PHPUnit Integration Tests
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh test:phpunit
  zip:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: *PLUGIN_PATH
      - run:
          name: Installing Pluginade
          working_directory: *PLUGIN_PATH
          command: sh pluginade.sh install
      - setup_remote_docker
      - run:
          name: Creating the zip file
          working_directory: *PLUGIN_PATH
          command: |
            sh pluginade.sh build
            sh pluginade.sh zip
            mkdir /tmp/artifacts
            mv pattern-manager*.zip /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
  svn-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: *PLUGIN_PATH
      - node/install:
          node-version: '14'
      - run:
          name: Building the plugin
          working_directory: *PLUGIN_PATH
          command: |
            sh pluginade.sh build
      - wp-svn/deploy-plugin:
          plugin-path: *PLUGIN_PATH
          wporg-assets-directory: wporg

workflows:
  build:
    jobs:
      - lint
      - test-js
      - phpunit
          # matrix:
          #   parameters:
          #     php-version: [ '7.4', '8.0', '8.1', '8.2' ]
      - zip
      - wp-svn/check-versions:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: /^bump\/.*/
      - svn-deploy:
          context: genesis-svn
          requires:
            - wp-svn/check-versions
            - lint
            - test-js
            - phpunit
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - lint
            - test-js
            - phpunit
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
