version: 2.1

jobs:
  php-lint:
    docker:
      - image: cimg/php:7.3
    steps:
      - checkout
      - run:
          name: Linting PHP
          command: |
            composer i
            composer lint

workflows:
  build:
    jobs:
      - php-lint
